#ifndef PRIORITIES_H
#define PRIORITIES_H

enum Priorities {
    TEMPERATURE_CONTROL_PRIO = 1,
    HUMIDITY_CONTROL_PRIO,
    CO2_CONTROL_PRIO,
    MOTOR_CONTROL_PRIO,
    LCD_DISPLAY_PRIO,
    //VENTILATION_CONTROL_PRIO,
    ALARM_CONTROL_PRIO,
    HATCH_MODE_PRIO
};

#endif // PRIORITIES_H


